kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: k8s-otel

patches:
  - target:
      kind: SecurityContextConstraints
      name: otel-scc 
    patch: |-
      - op: replace
        path: /users/0
        value: system:serviceaccount:k8s-otel:otel

resources:
  - namespace.yaml
  - service-account.yaml
  - cluster-role-bindings.yaml
  - cluster-role.yaml
  - scc.yaml
  - config-maps.yaml
  - opentelemetry-collector.yaml

